/*
 * Created 31-May-2012
 * 
 * Copyright Samuel Halliday 2012
 * PROPRIETARY/CONFIDENTIAL. Use is subject to licence terms.
 */
package uk.me.fommil.zibaldone.desktop;

import javax.swing.JPanel;
import org.jdesktop.swingx.JXButton;

/**
 * The parts of {@link ImporterView} that can be set by the Netbeans GUI Editor.
 *
 * @author Samuel Halliday
 */
public class ImporterViewForm extends javax.swing.JPanel {

    public ImporterViewForm() {
        initComponents();
    }

    // <editor-fold defaultstate="collapsed" desc="BOILERPLATE GETTERS/SETTERS">
    public JPanel getjPropertiesPanel() {
        return jPropertiesPanel;
    }

    public JXButton getjXReloadButton() {
        return jXReloadButton;
    }

    public JXButton getjXRemoveButton() {
        return jXRemoveButton;
    }
    // </editor-fold>

    /**
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPropertiesPanel = new javax.swing.JPanel();
        jXReloadButton = new org.jdesktop.swingx.JXButton();
        jXRemoveButton = new org.jdesktop.swingx.JXButton();

        jPropertiesPanel.setLayout(new java.awt.GridLayout(0, 2));

        jXReloadButton.setText("Reload");

        jXRemoveButton.setText("Remove");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPropertiesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jXReloadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXRemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXReloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPropertiesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPropertiesPanel;
    private org.jdesktop.swingx.JXButton jXReloadButton;
    private org.jdesktop.swingx.JXButton jXRemoveButton;
    // End of variables declaration//GEN-END:variables
}
