/*
 * Created 24-May-2012
 * 
 * Copyright Samuel Halliday 2012
 * PROPRIETARY/CONFIDENTIAL. Use is subject to licence terms.
 */
package uk.me.fommil.zibaldone.desktop;

import edu.uci.ics.jung.graph.ObservableGraph;
import edu.uci.ics.jung.graph.SparseMultigraph;
import uk.me.fommil.zibaldone.Note;

/**
 * @author Samuel Halliday
 */
public class Mainscreen extends javax.swing.JFrame {

    /**
     * @return a suitable model for use in GUI Editors such as in Netbeans.
     */
    static ObservableGraph<Note, Double> getGraphForTheBenefitOfNetbeans() {
        ObservableGraph<Note, Double> graph = new ObservableGraph<Note, Double>(new SparseMultigraph<Note, Double>());

        // TODO: some nice Notes/edges for display

        return graph;
    }
    private final JungMainController controller;

    /**
     * @deprecated only to be used by GUI Editors.
     */
    @Deprecated
    public Mainscreen() {
        this(getGraphForTheBenefitOfNetbeans());
    }

    public Mainscreen(ObservableGraph<Note, Double> graph) {
        initComponents();

        controller = new JungMainController(graph);
    }

    /**
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jButtonRefresh = new javax.swing.JButton();
        jButtonClusters = new javax.swing.JButton();
        jSearch = new org.jdesktop.swingx.JXSearchField();
        jCloudButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonSynonyms = new javax.swing.JButton();
        jButtonSources = new javax.swing.JButton();
        jFauxPanel = new javax.swing.JPanel();
        jImportersPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar.setFloatable(false);
        jToolBar.setRollover(true);
        jToolBar.setBorderPainted(false);

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.setFocusable(false);
        jButtonRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar.add(jButtonRefresh);

        jButtonClusters.setText("Clusters");
        jButtonClusters.setFocusable(false);
        jButtonClusters.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClusters.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar.add(jButtonClusters);
        jToolBar.add(jSearch);

        jCloudButton.setText("Tags");
        jToolBar.add(jCloudButton);

        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 1));
        jToolBar.add(jSeparator1);

        jButtonSynonyms.setText("Synonyms");
        jToolBar.add(jButtonSynonyms);

        jButtonSources.setText("Importers");
        jButtonSources.setFocusable(false);
        jButtonSources.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSources.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSources.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSourcesMouseClicked(evt);
            }
        });
        jToolBar.add(jButtonSources);

        jFauxPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jImportersPanelLayout = new javax.swing.GroupLayout(jImportersPanel);
        jImportersPanel.setLayout(jImportersPanelLayout);
        jImportersPanelLayout.setHorizontalGroup(
            jImportersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        jImportersPanelLayout.setVerticalGroup(
            jImportersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFauxPanelLayout = new javax.swing.GroupLayout(jFauxPanel);
        jFauxPanel.setLayout(jFauxPanelLayout);
        jFauxPanelLayout.setHorizontalGroup(
            jFauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFauxPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jImportersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jFauxPanelLayout.setVerticalGroup(
            jFauxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImportersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addComponent(jFauxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFauxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSourcesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSourcesMouseClicked
        jImportersPanel.setVisible(!jImportersPanel.isVisible());
    }//GEN-LAST:event_jButtonSourcesMouseClicked

    /** @param args */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                ObservableGraph<Note, Double> graph = new ObservableGraph<Note, Double>(new SparseMultigraph<Note, Double>());

                Mainscreen main = new Mainscreen(graph);
                main.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClusters;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSources;
    private javax.swing.JButton jButtonSynonyms;
    private javax.swing.JButton jCloudButton;
    private javax.swing.JPanel jFauxPanel;
    private javax.swing.JPanel jImportersPanel;
    private org.jdesktop.swingx.JXSearchField jSearch;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
}
